baseURL: "https://blog.seangransee.com"
languageCode: "en-us"
title: "Sean Gransee"
permalinks:
  posts: /:year/:month/:title/
googleAnalytics: UA-1016807-11
disqusShortname: seangransee
theme: "hemingway2"
params:
  prism:
    languages:
      - bash
      - yaml
  social:
    - url: "https://github.com/seangransee"
      fa_icon: "fa-github"
    - url: "https://twitter.com/seangransee"
      fa_icon: "fa-twitter"
    - url: "https://www.instagram.com/seangransee/"
      fa_icon: "fa-instagram"
    - url: "mailto:sean.gransee@gmail.com"
      fa_icon: "fa-envelope"
